"""Access and Access database engine reserved words.

Source: Microsoft Support, "Learn about Access reserved words and symbols" (retrieved 2026-09-26). Using
these as object or field names is legal but causes errors in expressions, SQL and VBA unless every
reference is bracketed, so PyAccessKit warns about them (``AccessNameWarning``).
"""

from __future__ import annotations

_ACCESS = """
ADD ALL Alphanumeric ALTER AND ANY Application AS ASC Assistant AUTOINCREMENT Avg BETWEEN BINARY BIT
BOOLEAN BY BYTE CHAR CHARACTER COLUMN CompactDatabase CONSTRAINT Container Count COUNTER CREATE
CreateDatabase CreateField CreateGroup CreateIndex CreateObject CreateProperty CreateRelation
CreateTableDef CreateUser CreateWorkspace CURRENCY CurrentUser DATABASE DATE DATETIME DELETE DESC
Description DISALLOW DISTINCT DISTINCTROW Document DOUBLE DROP Echo Else End Eqv Error EXISTS Exit FALSE
Field Fields FillCache FLOAT FLOAT4 FLOAT8 FOREIGN Form Forms FROM Full FUNCTION GENERAL GetObject
GetOption GotoPage GROUP GUID HAVING Idle IEEEDOUBLE IEEESINGLE If IGNORE Imp IN INDEX Indexes INNER
INSERT InsertText INT INTEGER INTEGER1 INTEGER2 INTEGER4 INTO IS JOIN KEY LastModified LEFT Level Like
LOGICAL LOGICAL1 LONG LONGBINARY LONGTEXT Macro Match Max Min Mod MEMO Module MONEY Move NAME
NewPassword NO Not Note NULL NUMBER NUMERIC Object OLEOBJECT OFF ON OpenRecordset OPTION OR ORDER
Orientation Outer OWNERACCESS Parameter PARAMETERS Partial PERCENT PIVOT PRIMARY PROCEDURE Property
Queries Query Quit REAL Recalc Recordset REFERENCES Refresh RefreshLink RegisterDatabase Relation Repaint
RepairDatabase Report Reports Requery RIGHT SCREEN SECTION SELECT SET SetFocus SetOption SHORT SINGLE
SMALLINT SOME SQL StDev StDevP STRING Sum TABLE TableDef TableDefs TableID TEXT TIME TIMESTAMP TOP
TRANSFORM TRUE Type UNION UNIQUE UPDATE USER VALUE VALUES Var VarP VARBINARY VARCHAR WHERE WITH Workspace
Xor Year YES YESNO
"""

_ENGINE = """
ABSOLUTE ACTION ADD ADMINDB ALL ALLOCATE ALPHANUMERIC ALTER AND ANY ARE AS ASC ASSERTION AT AUTHORIZATION
AUTOINCREMENT AVG BAND BEGIN BETWEEN BINARY BIT BIT_LENGTH BNOT BOR BOTH BXOR BY BYTE CASCADE CASCADED
CASE CAST CATALOG CHAR CHARACTER CHAR_LENGTH CHARACTER_LENGTH CHECK CLOSE COALESCE COLLATE COLLATION
COLUMN COMMIT COMP COMPRESSION CONNECT CONNECTION CONSTRAINT CONSTRAINTS CONTAINER CONTINUE CONVERT
CORRESPONDING COUNT COUNTER CREATE CREATEDB CROSS CURRENCY CURRENT CURRENT_DATE CURRENT_TIME
CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DATE DATETIME DAY DEALLOCATE DEC DECIMAL DECLARE DEFAULT
DEFERRABLE DEFERRED DELETE DESC DESCRIBE DESCRIPTOR DIAGNOSTICS DISALLOW DISCONNECT DISTINCT DOMAIN
DOUBLE DROP ELSE END END-EXEC ESCAPE EXCEPT EXCEPTION EXCLUSIVECONNECT EXEC EXECUTE EXISTS EXTERNAL
EXTRACT FALSE FETCH FIRST FLOAT FLOAT4 FLOAT8 FOR FOREIGN FOUND FROM FULL GENERAL GET GLOBAL GO GOTO
GRANT GROUP GUID HAVING HOUR IDENTITY IEEEDOUBLE IEEESINGLE IGNORE IMAGE IMMEDIATE IN INDEX INDICATOR
INHERITABLE INITIALLY INNER INPUT INSENSITIVE INSERT INT INTEGER INTEGER1 INTEGER2 INTEGER4 INTERSECT
INTERVAL INTO IS ISOLATION JOIN KEY LANGUAGE LAST LEADING LEFT LEVEL LIKE LOCAL LOGICAL LOGICAL1 LONG
LONGBINARY LONGCHAR LONGTEXT LOWER MATCH MAX MEMO MIN MINUTE MODULE MONEY MONTH NAMES NATIONAL NATURAL
NCHAR NEXT NO NOT NOTE NULL NULLIF NUMBER NUMERIC OBJECT OCTET_LENGTH OF OLEOBJECT ON ONLY OPEN OPTION
OR ORDER OUTER OUTPUT OVERLAPS OWNERACCESS PAD PARAMETERS PARTIAL PASSWORD PERCENT PIVOT POSITION
PRECISION PREPARE PRESERVE PRIMARY PRIOR PRIVILEGES PROC PROCEDURE PUBLIC READ REAL REFERENCES RELATIVE
RESTRICT REVOKE RIGHT ROLLBACK ROWS SCHEMA SCROLL SECOND SECTION SELECT SELECTSCHEMA SELECTSECURITY
SESSION SESSION_USER SET SHORT SINGLE SIZE SMALLINT SOME SPACE SQL SQLCODE SQLERROR SQLSTATE STRING
SUBSTRING SUM SYSTEM_USER TABLE TABLEID TEMPORARY TEXT THEN TIME TIMESTAMP TIMEZONE_HOUR TIMEZONE_MINUTE
TO TOP TRAILING TRANSACTION TRANSFORM TRANSLATE TRANSLATION TRIM TRUE UNION UNIQUE UNIQUEIDENTIFIER
UNKNOWN UPDATE UPDATEIDENTITY UPDATEOWNER UPDATESECURITY UPPER USAGE USER USING VALUE VALUES VARBINARY
VARCHAR VARYING VIEW WHEN WHENEVER WHERE WITH WORK WRITE YEAR YESNO ZONE
"""

RESERVED_WORDS: frozenset[str] = frozenset(word.casefold() for word in (_ACCESS + _ENGINE).split())
"""Case-folded Access + Access database engine reserved words."""
