"""Access and DAO constants used by PyAccessKit's COM adapters (internal).

Generated by ``scripts/gen_constants.py`` from the installed type libraries — do not edit by hand.

* Microsoft Access 16.0 Object Library — ``{4AFFC9A0-5F99-101B-AF4E-00AA003F0F07}`` v9.0
* Microsoft Office 16.0 Access database engine Object Library — ``{4AC9E1DA-5BAD-4AC7-86E3-24F4CDCECA28}`` v12.0
"""

# ruff: noqa: N815
from __future__ import annotations

from enum import IntEnum


class AcCloseSave(IntEnum):
    """``AcCloseSave`` (Microsoft Access 16.0 Object Library)."""

    acSavePrompt = 0
    acSaveYes = 1
    acSaveNo = 2


class AcControlType(IntEnum):
    """``AcControlType`` (Microsoft Access 16.0 Object Library)."""

    acLabel = 100
    acRectangle = 101
    acLine = 102
    acImage = 103
    acCommandButton = 104
    acOptionButton = 105
    acCheckBox = 106
    acOptionGroup = 107
    acBoundObjectFrame = 108
    acTextBox = 109
    acListBox = 110
    acComboBox = 111
    acSubform = 112
    acObjectFrame = 114
    acPageBreak = 118
    acCustomControl = 119
    acToggleButton = 122
    acTabCtl = 123
    acPage = 124
    acAttachment = 126
    acEmptyCell = 127
    acWebBrowser = 128
    acNavigationControl = 129
    acNavigationButton = 130
    acChart = 133
    acEdgeBrowser = 134


class AcDefView(IntEnum):
    """``AcDefView`` (Microsoft Access 16.0 Object Library)."""

    acDefViewSingle = 0
    acDefViewContinuous = 1
    acDefViewDatasheet = 2
    acDefViewPivotTable = 3
    acDefViewPivotChart = 4
    acDefViewSplitForm = 5


class AcFormOpenDataMode(IntEnum):
    """``AcFormOpenDataMode`` (Microsoft Access 16.0 Object Library)."""

    acFormPropertySettings = -1
    acFormAdd = 0
    acFormEdit = 1
    acFormReadOnly = 2


class AcFormView(IntEnum):
    """``AcFormView`` (Microsoft Access 16.0 Object Library)."""

    acNormal = 0
    acDesign = 1
    acPreview = 2
    acFormDS = 3
    acFormPivotTable = 4
    acFormPivotChart = 5
    acLayout = 6


class AcModuleType(IntEnum):
    """``AcModuleType`` (Microsoft Access 16.0 Object Library)."""

    acStandardModule = 0
    acClassModule = 1


class AcNewDatabaseFormat(IntEnum):
    """``AcNewDatabaseFormat`` (Microsoft Access 16.0 Object Library)."""

    acNewDatabaseFormatUserDefault = 0
    acNewDatabaseFormatAccess2000 = 9
    acNewDatabaseFormatAccess2002 = 10
    acNewDatabaseFormatAccess2007 = 12


class AcObjectType(IntEnum):
    """``AcObjectType`` (Microsoft Access 16.0 Object Library)."""

    acDefault = -1
    acTable = 0
    acQuery = 1
    acForm = 2
    acReport = 3
    acMacro = 4
    acModule = 5
    acDataAccessPage = 6
    acServerView = 7
    acDiagram = 8
    acStoredProcedure = 9
    acFunction = 10
    acDatabaseProperties = 11
    acTableDataMacro = 12


class AcQuitOption(IntEnum):
    """``AcQuitOption`` (Microsoft Access 16.0 Object Library)."""

    acQuitPrompt = 0
    acQuitSaveAll = 1
    acQuitSaveNone = 2


class AcSection(IntEnum):
    """``AcSection`` (Microsoft Access 16.0 Object Library)."""

    acDetail = 0
    acHeader = 1
    acFooter = 2
    acPageHeader = 3
    acPageFooter = 4
    acGroupLevel1Header = 5
    acGroupLevel1Footer = 6
    acGroupLevel2Header = 7
    acGroupLevel2Footer = 8


class AcSysCmdAction(IntEnum):
    """``AcSysCmdAction`` (Microsoft Access 16.0 Object Library)."""

    acSysCmdInitMeter = 1
    acSysCmdUpdateMeter = 2
    acSysCmdRemoveMeter = 3
    acSysCmdSetStatus = 4
    acSysCmdClearStatus = 5
    acSysCmdRuntime = 6
    acSysCmdAccessVer = 7
    acSysCmdIniFile = 8
    acSysCmdAccessDir = 9
    acSysCmdGetObjectState = 10
    acSysCmdClearHelpTopic = 11
    acSysCmdProfile = 12
    acSysCmdGetWorkgroupFile = 13
    acSysCmdCompile = 603
    acSysCmdGetMsoBuildNumber = 715
    acSysCmdGetFullVersion = 720
    acSysCmdGetVersion = 721
    acSysCmdGetFullBuildNumber = 722
    acSysCmdGetChannelName = 723
    acSysCmdGetBitness = 724
    acSysCmdGetBuildNumber = 725


class AcView(IntEnum):
    """``AcView`` (Microsoft Access 16.0 Object Library)."""

    acViewNormal = 0
    acViewDesign = 1
    acViewPreview = 2
    acViewPivotTable = 3
    acViewPivotChart = 4
    acViewReport = 5
    acViewLayout = 6
    acViewSql = 7


class AcWindowMode(IntEnum):
    """``AcWindowMode`` (Microsoft Access 16.0 Object Library)."""

    acWindowNormal = 0
    acHidden = 1
    acIcon = 2
    acDialog = 3


class DataTypeEnum(IntEnum):
    """``DataTypeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbBoolean = 1
    dbByte = 2
    dbInteger = 3
    dbLong = 4
    dbCurrency = 5
    dbSingle = 6
    dbDouble = 7
    dbDate = 8
    dbBinary = 9
    dbText = 10
    dbLongBinary = 11
    dbMemo = 12
    dbGUID = 15
    dbBigInt = 16
    dbVarBinary = 17
    dbChar = 18
    dbNumeric = 19
    dbDecimal = 20
    dbFloat = 21
    dbTime = 22
    dbTimeStamp = 23
    dbDateTimeExtended = 26
    dbAttachment = 101
    dbComplexByte = 102
    dbComplexInteger = 103
    dbComplexLong = 104
    dbComplexSingle = 105
    dbComplexDouble = 106
    dbComplexGUID = 107
    dbComplexDecimal = 108
    dbComplexText = 109


class DatabaseTypeEnum(IntEnum):
    """``DatabaseTypeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbVersion10 = 1
    dbEncrypt = 2
    dbDecrypt = 4
    dbVersion11 = 8
    dbVersion20 = 16
    dbVersion30 = 32
    dbVersion40 = 64
    dbVersion120 = 128
    dbVersion140 = 256
    dbVersion150 = 512
    dbVersion167 = 1024


class FieldAttributeEnum(IntEnum):
    """``FieldAttributeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbFixedField = 1
    dbVariableField = 2
    dbAutoIncrField = 16
    dbUpdatableField = 32
    dbSystemField = 8192
    dbHyperlinkField = 32768
    dbDescending = 1


class QueryDefTypeEnum(IntEnum):
    """``QueryDefTypeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbQSelect = 0
    dbQProcedure = 224
    dbQAction = 240
    dbQCrosstab = 16
    dbQDelete = 32
    dbQUpdate = 48
    dbQAppend = 64
    dbQMakeTable = 80
    dbQDDL = 96
    dbQSQLPassThrough = 112
    dbQSetOperation = 128
    dbQSPTBulk = 144
    dbQCompound = 160


class RecordsetOptionEnum(IntEnum):
    """``RecordsetOptionEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbDenyWrite = 1
    dbDenyRead = 2
    dbReadOnly = 4
    dbAppendOnly = 8
    dbInconsistent = 16
    dbConsistent = 32
    dbSQLPassThrough = 64
    dbFailOnError = 128
    dbForwardOnly = 256
    dbSeeChanges = 512
    dbRunAsync = 1024
    dbExecDirect = 2048


class RecordsetTypeEnum(IntEnum):
    """``RecordsetTypeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbOpenTable = 1
    dbOpenDynaset = 2
    dbOpenSnapshot = 4
    dbOpenForwardOnly = 8
    dbOpenDynamic = 16


class RelationAttributeEnum(IntEnum):
    """``RelationAttributeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbRelationUnique = 1
    dbRelationDontEnforce = 2
    dbRelationInherited = 4
    dbRelationUpdateCascade = 256
    dbRelationDeleteCascade = 4096
    dbRelationLeft = 16777216
    dbRelationRight = 33554432


class TableDefAttributeEnum(IntEnum):
    """``TableDefAttributeEnum`` (Microsoft Office 16.0 Access database engine Object Library)."""

    dbAttachExclusive = 65536
    dbAttachSavePWD = 131072
    dbSystemObject = -2147483646
    dbAttachedTable = 1073741824
    dbAttachedODBC = 536870912
    dbHiddenObject = 1


# LanguageConstants (Microsoft Office 16.0 Access database engine Object Library)
dbLangArabic = ';LANGID=0x0401;CP=1256;COUNTRY=0'
dbLangCzech = ';LANGID=0x0405;CP=1250;COUNTRY=0'
dbLangDutch = ';LANGID=0x0413;CP=1252;COUNTRY=0'
dbLangGeneral = ';LANGID=0x0409;CP=1252;COUNTRY=0'
dbLangGreek = ';LANGID=0x0408;CP=1253;COUNTRY=0'
dbLangHebrew = ';LANGID=0x040D;CP=1255;COUNTRY=0'
dbLangHungarian = ';LANGID=0x040E;CP=1250;COUNTRY=0'
dbLangIcelandic = ';LANGID=0x040F;CP=1252;COUNTRY=0'
dbLangNordic = ';LANGID=0x041D;CP=1252;COUNTRY=0'
dbLangNorwDan = ';LANGID=0x0406;CP=1252;COUNTRY=0'
dbLangPolish = ';LANGID=0x0415;CP=1250;COUNTRY=0'
dbLangCyrillic = ';LANGID=0x0419;CP=1251;COUNTRY=0'
dbLangSpanish = ';LANGID=0x040A;CP=1252;COUNTRY=0'
dbLangSwedFin = ';LANGID=0x041D;CP=1252;COUNTRY=0'
dbLangTurkish = ';LANGID=0x041F;CP=1254;COUNTRY=0'
dbLangJapanese = ';LANGID=0x0411;CP=932;COUNTRY=0'
dbLangChineseSimplified = ';LANGID=0x0804;CP=936;COUNTRY=0'
dbLangChineseTraditional = ';LANGID=0x0404;CP=950;COUNTRY=0'
dbLangKorean = ';LANGID=0x0412;CP=949;COUNTRY=0'
dbLangThai = ';LANGID=0x041E;CP=874;COUNTRY=0'
dbLangSlovenian = ';LANGID=0x0424;CP=1250;COUNTRY=0'
dbLangJapaneseRadicalStrokeCount = ';LANGID=0x00040411;CP=65001;COUNTRY=0'
dbLangHindi = ';LANGID=0x00000439;CP=65001;COUNTRY=0'


class MsoAutomationSecurity(IntEnum):
    """``Application.AutomationSecurity`` values (Office core type library)."""

    msoAutomationSecurityLow = 1
    msoAutomationSecurityByUI = 2
    msoAutomationSecurityForceDisable = 3


class AdoSchema(IntEnum):
    """ADO ``SchemaEnum`` values used for column introspection."""

    adSchemaColumns = 4
    adSchemaIndexes = 12


class FormScrollBars(IntEnum):
    """Values of the Access ``Form.ScrollBars`` property."""

    neither = 0
    horizontal = 1
    vertical = 2
    both = 3


class TextFormat(IntEnum):
    """Values of the Access ``TextFormat`` field property (Long Text)."""

    plain_text = 0
    rich_text = 1


# Well-known Win32/COM HRESULTs (as signed 32-bit integers, the way pywin32 reports them).
def _hresult(value: int) -> int:
    return value - 0x1_0000_0000 if value & 0x8000_0000 else value


DISP_E_EXCEPTION = _hresult(0x80020009)
REGDB_E_CLASSNOTREG = _hresult(0x80040154)
CO_E_SERVER_EXEC_FAILURE = _hresult(0x80080005)
RPC_E_CALL_REJECTED = _hresult(0x80010001)
RPC_E_SERVERCALL_RETRYLATER = _hresult(0x8001010A)
RPC_E_DISCONNECTED = _hresult(0x80010108)
RPC_E_SERVERFAULT = _hresult(0x80010105)
RPC_S_SERVER_UNAVAILABLE = _hresult(0x800706BA)
RPC_S_CALL_FAILED = _hresult(0x800706BE)
CO_E_OBJNOTCONNECTED = _hresult(0x800401FD)
