"""PyAccessKit: a modern, typed, Pythonic toolkit for Microsoft Access databases and applications.

Quick start::

    from pyaccesskit import AccessDatabase, Column

    with AccessDatabase.create("crm.accdb") as db:
        db.tables.create(
            "Customers",
            columns=[
                Column.autonumber("CustomerID", primary_key=True),
                Column.text("CustomerName", length=200, required=True),
            ],
        )
"""

from pyaccesskit._version import __version__
from pyaccesskit.database import AccessDatabase
from pyaccesskit.diagnostics import Diagnosis, diagnose
from pyaccesskit.enums import (
    ControlKind,
    DataType,
    DialogPolicy,
    Engine,
    FormView,
    JoinType,
    LayoutKind,
    MacroSecurity,
    ModuleKind,
    NumberSize,
    ObjectKind,
    PropertyType,
    QueryKind,
    RowSourceType,
    ScrollBars,
    Section,
    Transport,
)
from pyaccesskit.errors import (
    AccessApplicationError,
    AccessDialogError,
    AccessDialogWarning,
    AccessNameWarning,
    AccessNotInstalledError,
    AccessProcessDiedError,
    AccessRuntimeOnlyError,
    AccessTimeoutError,
    CapabilityError,
    CleanupError,
    ComError,
    DaoNotAvailableError,
    DatabaseError,
    DatabaseExistsError,
    DatabaseLockedError,
    DatabaseNotFoundError,
    EngineUnavailableError,
    EnvironmentProblem,
    IntegrityViolationError,
    InvalidPasswordError,
    MissingParameterError,
    ObjectError,
    ObjectExistsError,
    ObjectInUseError,
    ObjectNotFoundError,
    PyAccessKitError,
    QueryError,
    ReadOnlyError,
    RelationshipError,
    SchemaError,
    SessionClosedError,
    SessionError,
    SpecError,
    SqlSyntaxError,
    UnrecognizedFormatError,
    WrongThreadError,
)
from pyaccesskit.forms import FormBuilder, FormSpec, Vba
from pyaccesskit.maintenance import reap_orphans
from pyaccesskit.options import SessionOptions
from pyaccesskit.schema import (
    Column,
    Expr,
    IndexSpec,
    PassThroughOptions,
    QuerySpec,
    RelationshipSpec,
    TableSpec,
)
from pyaccesskit.units import Length, cm, inch, mm, pt, twips

__all__ = [
    "AccessApplicationError",
    "AccessDatabase",
    "AccessDialogError",
    "AccessDialogWarning",
    "AccessNameWarning",
    "AccessNotInstalledError",
    "AccessProcessDiedError",
    "AccessRuntimeOnlyError",
    "AccessTimeoutError",
    "CapabilityError",
    "CleanupError",
    "Column",
    "ComError",
    "ControlKind",
    "DaoNotAvailableError",
    "DataType",
    "DatabaseError",
    "DatabaseExistsError",
    "DatabaseLockedError",
    "DatabaseNotFoundError",
    "Diagnosis",
    "DialogPolicy",
    "Engine",
    "EngineUnavailableError",
    "EnvironmentProblem",
    "Expr",
    "FormBuilder",
    "FormSpec",
    "FormView",
    "IndexSpec",
    "IntegrityViolationError",
    "InvalidPasswordError",
    "JoinType",
    "LayoutKind",
    "Length",
    "MacroSecurity",
    "MissingParameterError",
    "ModuleKind",
    "NumberSize",
    "ObjectError",
    "ObjectExistsError",
    "ObjectInUseError",
    "ObjectKind",
    "ObjectNotFoundError",
    "PassThroughOptions",
    "PropertyType",
    "PyAccessKitError",
    "QueryError",
    "QueryKind",
    "QuerySpec",
    "ReadOnlyError",
    "RelationshipError",
    "RelationshipSpec",
    "RowSourceType",
    "SchemaError",
    "ScrollBars",
    "Section",
    "SessionClosedError",
    "SessionError",
    "SessionOptions",
    "SpecError",
    "SqlSyntaxError",
    "TableSpec",
    "Transport",
    "UnrecognizedFormatError",
    "Vba",
    "WrongThreadError",
    "__version__",
    "cm",
    "diagnose",
    "inch",
    "mm",
    "pt",
    "reap_orphans",
    "twips",
]
