"""Keep generated documentation in sync with its sources.

* The complete example in ``src/pyaccesskit/AGENT_GUIDE.md`` is copied from ``examples/04_inventory_app.py``
  (between the ``example:start`` / ``example:end`` markers), so the guide never shows untested code.
* ``docs/llms-full.txt`` concatenates the agent guide and the documentation pages for LLM tools
  (https://llmstxt.org). ``docs/llms.txt`` is the hand-written index.

Run ``python scripts/sync_docs.py`` after editing those sources; ``--check`` fails if anything is stale.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GUIDE = ROOT / "src" / "pyaccesskit" / "AGENT_GUIDE.md"
EXAMPLE = ROOT / "examples" / "04_inventory_app.py"
LLMS_FULL = ROOT / "docs" / "llms-full.txt"

# Pages included in llms-full.txt, in reading order (after the agent guide).
PAGES = [
    "index.md",
    "getting-started.md",
    "concepts/engines.md",
    "concepts/lifecycle.md",
    "concepts/specs.md",
    "guides/tables.md",
    "guides/relationships.md",
    "guides/queries.md",
    "guides/forms.md",
    "guides/modules.md",
    "guides/text-io.md",
    "guides/recipes.md",
    "reference/errors.md",
    "reference/data-types.md",
    "reference/cli.md",
    "environment.md",
    "faq.md",
]

_BLOCK = re.compile(r"(<!-- example:start -->\n).*?(<!-- example:end -->)", re.DOTALL)


def synced_guide() -> str:
    example = EXAMPLE.read_text(encoding="utf-8").rstrip("\n")
    guide = GUIDE.read_text(encoding="utf-8")
    if not _BLOCK.search(guide):
        raise SystemExit(f"{GUIDE}: example markers not found")
    return _BLOCK.sub(lambda m: f"{m.group(1)}```python\n{example}\n```\n{m.group(2)}", guide)


def llms_full(guide: str) -> str:
    parts = [
        "# PyAccessKit — full documentation for language models\n",
        "Generated by scripts/sync_docs.py. Start with the agent guide.\n",
        f"\n\n<!-- file: src/pyaccesskit/AGENT_GUIDE.md -->\n\n{guide.strip()}\n",
    ]
    for page in PAGES:
        text = (ROOT / "docs" / page).read_text(encoding="utf-8").strip()
        parts.append(f"\n\n<!-- file: docs/{page} -->\n\n{text}\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    args = parser.parse_args()
    guide = synced_guide()
    outputs = {GUIDE: guide, LLMS_FULL: llms_full(guide)}
    stale = [
        path
        for path, text in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)} (run python scripts/sync_docs.py)")
        return 1 if stale else 0
    for path in stale:
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
        print(f"updated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
